@url = http://localhost:4004


GET {{url}}/data/getData


GET {{url}}/BookshopService.getData()


GET {{url}}/bookshop
#GET {{url}}/demo/Foo

###

GET {{url}}/catalog
#GET {{url}}/my/Foo



POST {{url}}/my/Foo
Content-Type: application/json
{
    "name": 'Hello World!'
}


