@url = http://localhost:4004


GET {{url}}/my/PurchaseData?/groupby(maktl),aggregate(menge with max as maxMenge))


//GET {{url}}/my/PurchaseData?$apply=groupby((status),aggregate(status with countdistinct as total))

GET {{url}}/my/PurchaseData?$apply=filter(menge eq 49)/concat(aggregate($count as totalCount),groupby((maktx), aggregate($count as countPerYear)))



GET {{url}}/data/getData


GET {{url}}/BookshopService.getData()


GET {{url}}/bookshop
#GET {{url}}/demo/Foo

###

GET {{url}}/catalog
#GET {{url}}/my/Foo



POST {{url}}/my/Foo
Content-Type: application/json
{
    "name": 'Hello World!'
}


